### ISSUE TITLE
Wgpu fragment shader failed to compile error on startup

### ISSUE THREAD

**Issue by alex-smitg** [PolyMeilex/Neothesia#386]
Tried to run version 0.4 on Windows 10
Error message:
```[INFO  wgpu_jumpstart::gpu] Trying to initialize GPU with: Backends(NOOP | VULKAN | GL | METAL | DX12 | BROWSER_WEBGPU)
[INFO  wgpu_jumpstart::gpu] Using AMD Radeon HD 7660G (Gl, Preferred Format: Some(Rgba8UnormSrgb))
[ERROR wgpu_hal::gles::device]  Shader compilation failed: Fragment shader failed to compile with the following errors:
    ERROR: 0:12: error(#236) varying expected: gl_FragCoord
    ERROR: error(#273) 1 compilation errors.  No code generated


[ERROR wgpu::backend::wgpu_core] Shader translation error for stage ShaderStages(FRAGMENT): Fragment shader failed to compile with the following errors:
    ERROR: 0:12: error(#236) varying expected: gl_FragCoord
    ERROR: error(#273) 1 compilation errors.  No code generated


[ERROR wgpu::backend::wgpu_core] Please report it to https://github.com/gfx-rs/wgpu
[ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default

thread 'main' (4520) panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\wgpu-28.0.0\src\backend\wgpu_core.rs:1386:26:
wgpu error: Validation Error

Caused by:
  In Device::create_render_pipeline, label = 'glyphon pipeline'
    Internal error in ShaderStages(FRAGMENT) shader: Fragment shader failed to compile with the following errors:
ERROR: 0:12: error(#236) varying expected: gl_FragCoord
ERROR: error(#273) 1 compilation errors.  No code generated
```

Is my GPU is not supported?
Works on v0.2.

**Comment by PolyMeilex** [comment]
Hi, could you try the latest master build? There was a bunch of wgpu/glyphon changes since 0.4.

[windows-artifact(2).zip](https://github.com/user-attachments/files/29446898/windows-artifact.2.zip)

**Comment by alex-smitg** [comment]
Still not working. Same error.
